---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker image
      shell: docker pull 1651078/calculator_dev_ops

    - name: Restart a container
      docker_container:
        name: sci_calc
        image: 1651078/calculator_dev_ops
        state: started
        ports:
          - "8999:9000"
        tty: true
        detach: true
