---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker image
      shell: docker pull 1651078/calculator_dev_ops

    - name: running container
      shell: docker run -it -d --name sci_calc 1651078/calculator_dev_ops /bin/bash
      
    - name: attaching pseudo-TTY
      shell: docker attach sci_calc
